// <auto-generated />
using System;
using Assignment2_EFBasics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment2EFBasics.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Assignment2_EFBasics.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MeetingDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Schedule");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MeetingDate = "MWF",
                            Subject = "Maths",
                            Time = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            MeetingDate = "TT",
                            Subject = "Literature",
                            Time = new TimeSpan(0, 10, 30, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            MeetingDate = "MWF",
                            Subject = "Networking",
                            Time = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("Assignment2_EFBasics.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cohort")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cohort = "2022",
                            FirstName = "Nhi",
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 2,
                            Cohort = "2019",
                            FirstName = "Viet",
                            LastName = "Nguyen"
                        },
                        new
                        {
                            Id = 3,
                            Cohort = "2022",
                            FirstName = "Phi",
                            LastName = "Vo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
